version: '3.8'
services:
  readingisgooddb:
    image: postgres:13.2
    container_name: reading_is_good_db
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: "exit 0"
    hostname: postgres
    networks:
      - mynet
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=readingisgood
      - POSTGRES_DB=readingisgood
      - POSTGRES_HOST_AUTH_METHOD=trust

  app:
    build: .
    image: reading-is-good
    depends_on:
      - readingisgooddb
    ports:
      - "8080:8080"
    networks:
      - mynet
    restart: always
    healthcheck:
      test: "exit 0"

networks:
  mynet:
    name: my-shared-db-network